GET http://localhost:5000/get-attendance



###

POST http://localhost:5000/add-attendance
Content-Type: application/json

{
    
    "year" :"2002"
}

###

GET http://localhost:5000/get-leave-applications

###

POST http://localhost:5000/add-application
Content-Type: application/json

{
    "title" : "Diksha"
}

###

GET http://localhost:5000/

###

POST http://localhost:5000/signup
Content-Type: application/json

{
    "type" : "hr",
    "name" : "Diksha Buxani",
    "email" : "dikshabuxani@gmail.com",
    "password" : "123456"
} 
 
###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "dikshabuxani@gmail.com",
    "password" : "123456"
}

###

GET http://localhost:5000/get-all-payslips

###
POST http://localhost:5000/upload-payslip
Content-Type: application/json

###

GET http://localhost:5000/get-single-payslip/62ff4065826dd7492c3c1fed


###



PUT http://localhost:5000/update-single-payslip/62ff4065826dd7492c3c1fed
Content-Type: application/json

{
    "name":"Souvik Sen"
}



###

POST http://localhost:5000/employee-add
Content-Type: application/json

{
    "name":"Diksha "
}


### 
  

GET http://localhost:5000/get-employee-details
Content-Type: application/json

###

GET http://localhost:5000/get-single-employee/62fcb53d6f048d02020c2550

###


